version: '3.8'

services:
  web:
    build:
      context: flask_app
      dockerfile: Dockerfile_flask
    ports:
      - 5000:5000
    container_name: flask
  nginx:
    build: ./nginx
    ports:
      - 1337:80
    depends_on:
      - web
    container_name: nginx
